<template><div><h2 id="假随机数组词造句" tabindex="-1"><a class="header-anchor" href="#假随机数组词造句" aria-hidden="true">#</a> 假随机数组词造句</h2>
<p>在网上看到的，利用伪随机算法，通过设置特定的随机种子使生成的一系列特定数字，将数字对应的字符连起来可组成正常语义的词句。种子获取采用暴力搜索方法，一个一个数字试，看哪个数字生成的数字序列符合要求（自定义截止数字）</p>
<p>首先要控制随机数生成的区间，越大的区间随机到想要的数字的概率越低，符合要求的种子越难找，甚至有可能不存在</p>
<p>因为种子参数类型为<code v-pre>long</code>，故搜寻空间为<code v-pre>Long.MIN_VALUE ~ Long.MAX_VALUE</code>，再考虑到越短的数字看起来越简洁，故按照绝对值从小到大进行搜索</p>
<p>若待生成的词句为纯英文小写，则可利用 ASCII 码进行映射（<code v-pre>a ~ z &lt;--&gt; 97 ~ 123</code>），再考虑截止数字与区间的连续性，可取为 96。若待生成的词句为汉字则得用 Unicode 编码映射，但由于字符区间过长，很有可能找不到特定种子，不予实现</p>
<p>在进行稍长的查找时就会明显过长，后续可以考虑将区间分段用多线程分别同时查找</p>
<CodeTabs id="18" :data='[{"id":"demo"},{"id":"完整实现"}]' :active="1">
<template #title0="{ value, isActive }">demo</template>
<template #title1="{ value, isActive }">完整实现</template>
<template #tab0="{ value, isActive }">
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="shiki dark-plus" style="background-color: #1E1E1E" tabindex="0"><code><span class="line"><span style="color: #569CD6">import</span><span style="color: #D4D4D4"> java.util.Random;</span></span>
<span class="line"></span>
<span class="line"><span style="color: #569CD6">public</span><span style="color: #D4D4D4"> </span><span style="color: #569CD6">class</span><span style="color: #D4D4D4"> </span><span style="color: #4EC9B0">Whisper</span><span style="color: #D4D4D4"> {</span></span>
<span class="line"><span style="color: #D4D4D4">	</span><span style="color: #569CD6">public</span><span style="color: #D4D4D4"> </span><span style="color: #569CD6">static</span><span style="color: #D4D4D4"> </span><span style="color: #4EC9B0">void</span><span style="color: #D4D4D4"> </span><span style="color: #DCDCAA">main</span><span style="color: #D4D4D4">(</span><span style="color: #4EC9B0">String</span><span style="color: #D4D4D4">[] </span><span style="color: #9CDCFE">args</span><span style="color: #D4D4D4">) {</span></span>
<span class="line"><span style="color: #D4D4D4">		</span><span style="color: #4EC9B0">Random</span><span style="color: #D4D4D4"> </span><span style="color: #9CDCFE">creater</span><span style="color: #D4D4D4"> = </span><span style="color: #C586C0">new</span><span style="color: #D4D4D4"> </span><span style="color: #DCDCAA">Random</span><span style="color: #D4D4D4">();</span></span>
<span class="line"><span style="color: #D4D4D4">		</span><span style="color: #4EC9B0">long</span><span style="color: #D4D4D4">[] </span><span style="color: #9CDCFE">seeds</span><span style="color: #D4D4D4"> = { -</span><span style="color: #B5CEA8">95</span><span style="color: #D4D4D4">, -</span><span style="color: #B5CEA8">3871351</span><span style="color: #D4D4D4">, </span><span style="color: #B5CEA8">123439</span><span style="color: #D4D4D4">, -</span><span style="color: #B5CEA8">34025</span><span style="color: #D4D4D4">, -</span><span style="color: #B5CEA8">10835916</span><span style="color: #D4D4D4">, </span><span style="color: #B5CEA8">2009213</span><span style="color: #D4D4D4"> };</span></span>
<span class="line"><span style="color: #D4D4D4">		</span><span style="color: #4EC9B0">StringBuilder</span><span style="color: #D4D4D4"> </span><span style="color: #9CDCFE">sentence</span><span style="color: #D4D4D4"> = </span><span style="color: #C586C0">new</span><span style="color: #D4D4D4"> </span><span style="color: #DCDCAA">StringBuilder</span><span style="color: #D4D4D4">();</span></span>
<span class="line"><span style="color: #D4D4D4">		</span><span style="color: #C586C0">for</span><span style="color: #D4D4D4"> (</span><span style="color: #4EC9B0">long</span><span style="color: #D4D4D4"> </span><span style="color: #9CDCFE">seed</span><span style="color: #D4D4D4"> </span><span style="color: #C586C0">:</span><span style="color: #D4D4D4"> seeds) {</span></span>
<span class="line"><span style="color: #D4D4D4">			</span><span style="color: #9CDCFE">creater</span><span style="color: #D4D4D4">.</span><span style="color: #DCDCAA">setSeed</span><span style="color: #D4D4D4">(seed);</span></span>
<span class="line"><span style="color: #D4D4D4">			</span><span style="color: #C586C0">for</span><span style="color: #D4D4D4"> (</span><span style="color: #4EC9B0">int</span><span style="color: #D4D4D4"> </span><span style="color: #9CDCFE">code</span><span style="color: #D4D4D4"> = </span><span style="color: #9CDCFE">creater</span><span style="color: #D4D4D4">.</span><span style="color: #DCDCAA">nextInt</span><span style="color: #D4D4D4">(</span><span style="color: #B5CEA8">96</span><span style="color: #D4D4D4">, </span><span style="color: #B5CEA8">123</span><span style="color: #D4D4D4">); code != </span><span style="color: #B5CEA8">96</span><span style="color: #D4D4D4">; code = </span><span style="color: #9CDCFE">creater</span><span style="color: #D4D4D4">.</span><span style="color: #DCDCAA">nextInt</span><span style="color: #D4D4D4">(</span><span style="color: #B5CEA8">96</span><span style="color: #D4D4D4">, </span><span style="color: #B5CEA8">123</span><span style="color: #D4D4D4">))</span></span>
<span class="line"><span style="color: #D4D4D4">				</span><span style="color: #9CDCFE">sentence</span><span style="color: #D4D4D4">.</span><span style="color: #DCDCAA">append</span><span style="color: #D4D4D4">((</span><span style="color: #4EC9B0">char</span><span style="color: #D4D4D4">) code);</span></span>
<span class="line"><span style="color: #D4D4D4">			</span><span style="color: #9CDCFE">sentence</span><span style="color: #D4D4D4">.</span><span style="color: #DCDCAA">append</span><span style="color: #D4D4D4">(</span><span style="color: #CE9178">&#39; &#39;</span><span style="color: #D4D4D4">);</span></span>
<span class="line"><span style="color: #D4D4D4">		}</span></span>
<span class="line"><span style="color: #D4D4D4">		</span><span style="color: #9CDCFE">System</span><span style="color: #D4D4D4">.</span><span style="color: #9CDCFE">out</span><span style="color: #D4D4D4">.</span><span style="color: #DCDCAA">println</span><span style="color: #D4D4D4">(</span><span style="color: #9CDCFE">sentence</span><span style="color: #D4D4D4">.</span><span style="color: #DCDCAA">toString</span><span style="color: #D4D4D4">().</span><span style="color: #DCDCAA">stripTrailing</span><span style="color: #D4D4D4">());</span></span>
<span class="line"><span style="color: #D4D4D4">	}</span></span>
<span class="line"><span style="color: #D4D4D4">}</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></template>
<template #tab1="{ value, isActive }">
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="shiki dark-plus" style="background-color: #1E1E1E" tabindex="0"><code><span class="line"><span style="color: #569CD6">import</span><span style="color: #D4D4D4"> java.util.NoSuchElementException;</span></span>
<span class="line"><span style="color: #569CD6">import</span><span style="color: #D4D4D4"> java.util.Random;</span></span>
<span class="line"></span>
<span class="line"><span style="color: #569CD6">public</span><span style="color: #D4D4D4"> </span><span style="color: #569CD6">class</span><span style="color: #D4D4D4"> </span><span style="color: #4EC9B0">FakeRandom</span><span style="color: #D4D4D4"> {</span></span>
<span class="line"><span style="color: #D4D4D4">	</span><span style="color: #569CD6">private</span><span style="color: #D4D4D4"> </span><span style="color: #569CD6">static</span><span style="color: #D4D4D4"> </span><span style="color: #569CD6">final</span><span style="color: #D4D4D4"> </span><span style="color: #4EC9B0">Random</span><span style="color: #D4D4D4"> </span><span style="color: #9CDCFE">creater</span><span style="color: #D4D4D4"> = </span><span style="color: #C586C0">new</span><span style="color: #D4D4D4"> </span><span style="color: #DCDCAA">Random</span><span style="color: #D4D4D4">();</span></span>
<span class="line"><span style="color: #D4D4D4">	</span><span style="color: #569CD6">private</span><span style="color: #D4D4D4"> </span><span style="color: #569CD6">static</span><span style="color: #D4D4D4"> </span><span style="color: #4EC9B0">String</span><span style="color: #D4D4D4">[] </span><span style="color: #9CDCFE">words</span><span style="color: #D4D4D4"> = </span><span style="color: #C586C0">new</span><span style="color: #D4D4D4"> </span><span style="color: #4EC9B0">String</span><span style="color: #D4D4D4">[] { </span><span style="color: #CE9178">&quot;hello&quot;</span><span style="color: #D4D4D4">, </span><span style="color: #CE9178">&quot;world&quot;</span><span style="color: #D4D4D4"> };</span></span>
<span class="line"><span style="color: #D4D4D4">	</span><span style="color: #569CD6">private</span><span style="color: #D4D4D4"> </span><span style="color: #569CD6">static</span><span style="color: #D4D4D4"> </span><span style="color: #4EC9B0">long</span><span style="color: #D4D4D4">[] </span><span style="color: #9CDCFE">seeds</span><span style="color: #D4D4D4"> = </span><span style="color: #C586C0">new</span><span style="color: #D4D4D4"> </span><span style="color: #4EC9B0">long</span><span style="color: #D4D4D4">[] { -</span><span style="color: #B5CEA8">229985452L</span><span style="color: #D4D4D4">, -</span><span style="color: #B5CEA8">147909649L</span><span style="color: #D4D4D4"> };</span></span>
<span class="line"></span>
<span class="line"><span style="color: #6A9955">	/**</span></span>
<span class="line"><span style="color: #6A9955">	 * @description Find seed of each word with smallest abs and positive firstly.</span></span>
<span class="line"><span style="color: #6A9955">	 *              If the seed is not found, replaced by zero.</span></span>
<span class="line"><span style="color: #6A9955">	 *              The result will be stored in {@code seeds}.</span></span>
<span class="line"><span style="color: #6A9955">	 * </span><span style="color: #569CD6">@param</span><span style="color: #6A9955"> </span><span style="color: #9CDCFE">text</span><span style="color: #6A9955"> consists of a-z and space.</span></span>
<span class="line"><span style="color: #6A9955">	 * </span><span style="color: #569CD6">@throws</span><span style="color: #6A9955"> </span><span style="color: #4EC9B0">NoSuchElementException</span><span style="color: #6A9955"> indicate which word not found correspond seed.</span></span>
<span class="line"><span style="color: #6A9955">	 */</span></span>
<span class="line"><span style="color: #D4D4D4">	</span><span style="color: #569CD6">private</span><span style="color: #D4D4D4"> </span><span style="color: #569CD6">static</span><span style="color: #D4D4D4"> </span><span style="color: #4EC9B0">void</span><span style="color: #D4D4D4"> </span><span style="color: #DCDCAA">getSeed</span><span style="color: #D4D4D4">(</span><span style="color: #4EC9B0">String</span><span style="color: #D4D4D4"> </span><span style="color: #9CDCFE">text</span><span style="color: #D4D4D4">) {</span></span>
<span class="line"><span style="color: #D4D4D4">		words = </span><span style="color: #9CDCFE">text</span><span style="color: #D4D4D4">.</span><span style="color: #DCDCAA">split</span><span style="color: #D4D4D4">(</span><span style="color: #CE9178">&quot; &quot;</span><span style="color: #D4D4D4">);</span></span>
<span class="line"><span style="color: #D4D4D4">		seeds = </span><span style="color: #C586C0">new</span><span style="color: #D4D4D4"> </span><span style="color: #4EC9B0">long</span><span style="color: #D4D4D4">[</span><span style="color: #9CDCFE">words</span><span style="color: #D4D4D4">.</span><span style="color: #9CDCFE">length</span><span style="color: #D4D4D4">];</span></span>
<span class="line"><span style="color: #D4D4D4">		</span><span style="color: #C586C0">for</span><span style="color: #D4D4D4"> (</span><span style="color: #4EC9B0">int</span><span style="color: #D4D4D4"> </span><span style="color: #9CDCFE">i</span><span style="color: #D4D4D4"> = </span><span style="color: #B5CEA8">0</span><span style="color: #D4D4D4">; i &lt; </span><span style="color: #9CDCFE">words</span><span style="color: #D4D4D4">.</span><span style="color: #9CDCFE">length</span><span style="color: #D4D4D4">; ++i) {</span></span>
<span class="line"><span style="color: #D4D4D4">			</span><span style="color: #C586C0">for</span><span style="color: #D4D4D4"> (</span><span style="color: #4EC9B0">long</span><span style="color: #D4D4D4"> </span><span style="color: #9CDCFE">seed</span><span style="color: #D4D4D4"> = </span><span style="color: #B5CEA8">1L</span><span style="color: #D4D4D4">; seed &lt; </span><span style="color: #9CDCFE">Long</span><span style="color: #D4D4D4">.</span><span style="color: #9CDCFE">MAX_VALUE</span><span style="color: #D4D4D4">; ++seed) {</span></span>
<span class="line"><span style="color: #D4D4D4">				</span><span style="color: #C586C0">if</span><span style="color: #D4D4D4"> (</span><span style="color: #DCDCAA">isCorrespond</span><span style="color: #D4D4D4">(i, seed))</span></span>
<span class="line"><span style="color: #D4D4D4">					</span><span style="color: #C586C0">break</span><span style="color: #D4D4D4">;</span></span>
<span class="line"><span style="color: #D4D4D4">				</span><span style="color: #C586C0">if</span><span style="color: #D4D4D4"> (</span><span style="color: #DCDCAA">isCorrespond</span><span style="color: #D4D4D4">(i, -seed))</span></span>
<span class="line"><span style="color: #D4D4D4">					</span><span style="color: #C586C0">break</span><span style="color: #D4D4D4">;</span></span>
<span class="line"><span style="color: #D4D4D4">			}</span></span>
<span class="line"><span style="color: #D4D4D4">			</span><span style="color: #C586C0">if</span><span style="color: #D4D4D4"> (seeds[i] == </span><span style="color: #B5CEA8">0L</span><span style="color: #D4D4D4">)</span></span>
<span class="line"><span style="color: #D4D4D4">				</span><span style="color: #C586C0">throw</span><span style="color: #D4D4D4"> </span><span style="color: #C586C0">new</span><span style="color: #D4D4D4"> </span><span style="color: #DCDCAA">NoSuchElementException</span><span style="color: #D4D4D4">(</span><span style="color: #CE9178">&quot;The &quot;</span><span style="color: #D4D4D4"> + (i + </span><span style="color: #B5CEA8">1</span><span style="color: #D4D4D4">) + </span><span style="color: #CE9178">&quot; word find seed failed.&quot;</span><span style="color: #D4D4D4">);</span></span>
<span class="line"><span style="color: #D4D4D4">		}</span></span>
<span class="line"><span style="color: #D4D4D4">	}</span></span>
<span class="line"></span>
<span class="line"><span style="color: #6A9955">	/**</span></span>
<span class="line"><span style="color: #6A9955">	 * @description Check if the seed is corresponding to the word or not.</span></span>
<span class="line"><span style="color: #6A9955">	 *              If is correspond, set the seed directly.</span></span>
<span class="line"><span style="color: #6A9955">	 * </span><span style="color: #569CD6">@param</span><span style="color: #6A9955"> </span><span style="color: #9CDCFE">index</span><span style="color: #6A9955"> The index of word in {@code words}, as well as the index of</span></span>
<span class="line"><span style="color: #6A9955">	 *              seed in {@code words}.</span></span>
<span class="line"><span style="color: #6A9955">	 * </span><span style="color: #569CD6">@param</span><span style="color: #6A9955"> </span><span style="color: #9CDCFE">seed</span><span style="color: #6A9955">  The seed to be checked.</span></span>
<span class="line"><span style="color: #6A9955">	 * </span><span style="color: #569CD6">@return</span><span style="color: #6A9955"> True if seed is corresponding to word.</span></span>
<span class="line"><span style="color: #6A9955">	 */</span></span>
<span class="line"><span style="color: #D4D4D4">	</span><span style="color: #569CD6">private</span><span style="color: #D4D4D4"> </span><span style="color: #569CD6">static</span><span style="color: #D4D4D4"> </span><span style="color: #4EC9B0">boolean</span><span style="color: #D4D4D4"> </span><span style="color: #DCDCAA">isCorrespond</span><span style="color: #D4D4D4">(</span><span style="color: #4EC9B0">int</span><span style="color: #D4D4D4"> </span><span style="color: #9CDCFE">index</span><span style="color: #D4D4D4">, </span><span style="color: #4EC9B0">long</span><span style="color: #D4D4D4"> </span><span style="color: #9CDCFE">seed</span><span style="color: #D4D4D4">) {</span></span>
<span class="line"><span style="color: #D4D4D4">		</span><span style="color: #9CDCFE">creater</span><span style="color: #D4D4D4">.</span><span style="color: #DCDCAA">setSeed</span><span style="color: #D4D4D4">(seed);</span></span>
<span class="line"><span style="color: #D4D4D4">		</span><span style="color: #C586C0">for</span><span style="color: #D4D4D4"> (</span><span style="color: #4EC9B0">int</span><span style="color: #D4D4D4"> </span><span style="color: #9CDCFE">i</span><span style="color: #D4D4D4"> = </span><span style="color: #B5CEA8">0</span><span style="color: #D4D4D4">; i &lt; words[index].</span><span style="color: #DCDCAA">length</span><span style="color: #D4D4D4">(); ++i)</span></span>
<span class="line"><span style="color: #D4D4D4">			</span><span style="color: #C586C0">if</span><span style="color: #D4D4D4"> (words[index].</span><span style="color: #DCDCAA">charAt</span><span style="color: #D4D4D4">(i) != </span><span style="color: #9CDCFE">creater</span><span style="color: #D4D4D4">.</span><span style="color: #DCDCAA">nextInt</span><span style="color: #D4D4D4">(</span><span style="color: #B5CEA8">96</span><span style="color: #D4D4D4">, </span><span style="color: #B5CEA8">123</span><span style="color: #D4D4D4">))</span></span>
<span class="line"><span style="color: #D4D4D4">				</span><span style="color: #C586C0">return</span><span style="color: #D4D4D4"> </span><span style="color: #569CD6">false</span><span style="color: #D4D4D4">;</span></span>
<span class="line"><span style="color: #D4D4D4">		</span><span style="color: #C586C0">if</span><span style="color: #D4D4D4"> (</span><span style="color: #9CDCFE">creater</span><span style="color: #D4D4D4">.</span><span style="color: #DCDCAA">nextInt</span><span style="color: #D4D4D4">(</span><span style="color: #B5CEA8">96</span><span style="color: #D4D4D4">, </span><span style="color: #B5CEA8">123</span><span style="color: #D4D4D4">) == </span><span style="color: #B5CEA8">96</span><span style="color: #D4D4D4">) {</span></span>
<span class="line"><span style="color: #D4D4D4">			seeds[index] = seed;</span></span>
<span class="line"><span style="color: #D4D4D4">			</span><span style="color: #C586C0">return</span><span style="color: #D4D4D4"> </span><span style="color: #569CD6">true</span><span style="color: #D4D4D4">;</span></span>
<span class="line"><span style="color: #D4D4D4">		} </span><span style="color: #C586C0">else</span></span>
<span class="line"><span style="color: #D4D4D4">			</span><span style="color: #C586C0">return</span><span style="color: #D4D4D4"> </span><span style="color: #569CD6">false</span><span style="color: #D4D4D4">;</span></span>
<span class="line"><span style="color: #D4D4D4">	}</span></span>
<span class="line"></span>
<span class="line"><span style="color: #6A9955">	/**</span></span>
<span class="line"><span style="color: #6A9955">	 * @description Calculate text with {@code seeds} and output.</span></span>
<span class="line"><span style="color: #6A9955">	 */</span></span>
<span class="line"><span style="color: #D4D4D4">	</span><span style="color: #569CD6">private</span><span style="color: #D4D4D4"> </span><span style="color: #569CD6">static</span><span style="color: #D4D4D4"> </span><span style="color: #4EC9B0">void</span><span style="color: #D4D4D4"> </span><span style="color: #DCDCAA">printText</span><span style="color: #D4D4D4">() {</span></span>
<span class="line"><span style="color: #D4D4D4">		</span><span style="color: #4EC9B0">StringBuilder</span><span style="color: #D4D4D4"> </span><span style="color: #9CDCFE">sb</span><span style="color: #D4D4D4"> = </span><span style="color: #C586C0">new</span><span style="color: #D4D4D4"> </span><span style="color: #DCDCAA">StringBuilder</span><span style="color: #D4D4D4">();</span></span>
<span class="line"><span style="color: #D4D4D4">		</span><span style="color: #C586C0">for</span><span style="color: #D4D4D4"> (</span><span style="color: #4EC9B0">long</span><span style="color: #D4D4D4"> </span><span style="color: #9CDCFE">seed</span><span style="color: #D4D4D4"> </span><span style="color: #C586C0">:</span><span style="color: #D4D4D4"> seeds) {</span></span>
<span class="line"><span style="color: #D4D4D4">			</span><span style="color: #9CDCFE">creater</span><span style="color: #D4D4D4">.</span><span style="color: #DCDCAA">setSeed</span><span style="color: #D4D4D4">(seed);</span></span>
<span class="line"><span style="color: #D4D4D4">			</span><span style="color: #C586C0">for</span><span style="color: #D4D4D4"> (</span><span style="color: #4EC9B0">int</span><span style="color: #D4D4D4"> </span><span style="color: #9CDCFE">code</span><span style="color: #D4D4D4"> = </span><span style="color: #9CDCFE">creater</span><span style="color: #D4D4D4">.</span><span style="color: #DCDCAA">nextInt</span><span style="color: #D4D4D4">(</span><span style="color: #B5CEA8">96</span><span style="color: #D4D4D4">, </span><span style="color: #B5CEA8">123</span><span style="color: #D4D4D4">); code != </span><span style="color: #B5CEA8">96</span><span style="color: #D4D4D4">; code = </span><span style="color: #9CDCFE">creater</span><span style="color: #D4D4D4">.</span><span style="color: #DCDCAA">nextInt</span><span style="color: #D4D4D4">(</span><span style="color: #B5CEA8">96</span><span style="color: #D4D4D4">, </span><span style="color: #B5CEA8">123</span><span style="color: #D4D4D4">))</span></span>
<span class="line"><span style="color: #D4D4D4">				</span><span style="color: #9CDCFE">sb</span><span style="color: #D4D4D4">.</span><span style="color: #DCDCAA">append</span><span style="color: #D4D4D4">((</span><span style="color: #4EC9B0">char</span><span style="color: #D4D4D4">) code);</span></span>
<span class="line"><span style="color: #D4D4D4">			</span><span style="color: #9CDCFE">sb</span><span style="color: #D4D4D4">.</span><span style="color: #DCDCAA">append</span><span style="color: #D4D4D4">(</span><span style="color: #CE9178">&#39; &#39;</span><span style="color: #D4D4D4">);</span></span>
<span class="line"><span style="color: #D4D4D4">		}</span></span>
<span class="line"><span style="color: #D4D4D4">		</span><span style="color: #9CDCFE">System</span><span style="color: #D4D4D4">.</span><span style="color: #9CDCFE">out</span><span style="color: #D4D4D4">.</span><span style="color: #DCDCAA">println</span><span style="color: #D4D4D4">(</span><span style="color: #9CDCFE">sb</span><span style="color: #D4D4D4">.</span><span style="color: #DCDCAA">toString</span><span style="color: #D4D4D4">().</span><span style="color: #DCDCAA">stripTrailing</span><span style="color: #D4D4D4">());</span></span>
<span class="line"><span style="color: #D4D4D4">	}</span></span>
<span class="line"></span>
<span class="line"><span style="color: #D4D4D4">	</span><span style="color: #569CD6">public</span><span style="color: #D4D4D4"> </span><span style="color: #569CD6">static</span><span style="color: #D4D4D4"> </span><span style="color: #4EC9B0">void</span><span style="color: #D4D4D4"> </span><span style="color: #DCDCAA">main</span><span style="color: #D4D4D4">(</span><span style="color: #4EC9B0">String</span><span style="color: #D4D4D4">[] </span><span style="color: #9CDCFE">args</span><span style="color: #D4D4D4">) {</span></span>
<span class="line"><span style="color: #D4D4D4">		</span><span style="color: #DCDCAA">getSeed</span><span style="color: #D4D4D4">(</span><span style="color: #CE9178">&quot;the quick brown fox jumps over the lazy dog&quot;</span><span style="color: #D4D4D4">);</span></span>
<span class="line"><span style="color: #D4D4D4">		</span><span style="color: #C586C0">for</span><span style="color: #D4D4D4"> (</span><span style="color: #4EC9B0">int</span><span style="color: #D4D4D4"> </span><span style="color: #9CDCFE">i</span><span style="color: #D4D4D4"> = </span><span style="color: #B5CEA8">0</span><span style="color: #D4D4D4">; i &lt; </span><span style="color: #9CDCFE">seeds</span><span style="color: #D4D4D4">.</span><span style="color: #9CDCFE">length</span><span style="color: #D4D4D4">; ++i)</span></span>
<span class="line"><span style="color: #D4D4D4">			</span><span style="color: #9CDCFE">System</span><span style="color: #D4D4D4">.</span><span style="color: #9CDCFE">out</span><span style="color: #D4D4D4">.</span><span style="color: #DCDCAA">println</span><span style="color: #D4D4D4">(words[i] + </span><span style="color: #CE9178">&quot;</span><span style="color: #D7BA7D">\t</span><span style="color: #CE9178">&quot;</span><span style="color: #D4D4D4"> + seeds[i]);</span></span>
<span class="line"><span style="color: #D4D4D4">		</span><span style="color: #DCDCAA">printText</span><span style="color: #D4D4D4">();</span></span>
<span class="line"><span style="color: #D4D4D4">	}</span></span>
<span class="line"><span style="color: #D4D4D4">}</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></template>
</CodeTabs>
</div></template>


