export const pagesRoutes = [
  ["v-8daa1a0e","/",{"y":"h","t":"主页","i":"home"},["/index.html","/README.md"]],
  ["v-4a2605fe","/example/",{"y":"p","t":"写作参考","i":"creative"},["/example/index.html","/example/README.md"]],
  ["v-7d42e7fb","/example/sidebar.html",{"y":"p","t":"边栏目录样例","i":"typescript"},["/example/sidebar","/example/sidebar.md"]],
  ["v-7971eb74","/example/slide.html",{"y":"s","t":"幻灯片页","i":"slides"},["/example/slide","/example/slide.md"]],
  ["v-479edf49","/example/test.html",{"y":"p","t":"测试","i":"typescript"},["/example/test","/example/test.md"]],
  ["v-9caf75e6","/docs/essay/",{"y":"p","t":"说明"},["/docs/essay/index.html","/docs/essay/README.md"]],
  ["v-5f474719","/docs/essay/fake_random.html",{"y":"a","t":"假随机数组词造句"},["/docs/essay/fake_random","/docs/essay/fake_random.md"]],
  ["v-9ad09bde","/docs/essay/image_embed.html",{"y":"a","t":"图片隐写"},["/docs/essay/image_embed","/docs/essay/image_embed.md"]],
  ["v-2efce1da","/docs/essay/solution.html",{"y":"a","t":"日常小问题的解决"},["/docs/essay/solution","/docs/essay/solution.md"]],
  ["v-534edd30","/docs/algorithm/backtrack.html",{"y":"a","t":"回溯","i":"wrap"},["/docs/algorithm/backtrack","/docs/algorithm/backtrack.md"]],
  ["v-d843ef0a","/docs/algorithm/dynamic_programming.html",{"y":"a","t":"动态规划","i":"function"},["/docs/algorithm/dynamic_programming","/docs/algorithm/dynamic_programming.md"]],
  ["v-36d6919b","/docs/algorithm/greed.html",{"y":"a","t":"贪心","i":"bitbucket"},["/docs/algorithm/greed","/docs/algorithm/greed.md"]],
  ["v-e1eec494","/docs/algorithm/knowledge.html",{"y":"a","t":"算法讲解","i":"guide","O":1},["/docs/algorithm/knowledge","/docs/algorithm/knowledge.md"]],
  ["v-b2eb194a","/docs/algorithm/multi.html",{"y":"a","t":"二进制&哈希&多线程&并查集","i":"relation"},["/docs/algorithm/multi","/docs/algorithm/multi.md"]],
  ["v-5732fb76","/docs/algorithm/search.html",{"y":"a","t":"搜索","i":"search"},["/docs/algorithm/search","/docs/algorithm/search.md"]],
  ["v-eded1812","/docs/algorithm/simulation.html",{"y":"a","t":"模拟","i":"emmet"},["/docs/algorithm/simulation","/docs/algorithm/simulation.md"]],
  ["v-662f0bba","/docs/work/",{"y":"p","t":"说明"},["/docs/work/index.html","/docs/work/README.md"]],
  ["v-e9c246a2","/docs/work/java_knowlegde.html",{"y":"a","t":"Java 知识点"},["/docs/work/java_knowlegde","/docs/work/java_knowlegde.md"]],
  ["v-b89ed4ea","/docs/work/vim_tutor.html",{"y":"a","t":"Vim 简明教程"},["/docs/work/vim_tutor","/docs/work/vim_tutor.md"]],
  ["v-3706649a","/404.html",{"y":"p","t":""},["/404"]],
  ["v-147825fb","/docs/",{"y":"p","t":"Docs"},["/docs/index.html"]],
  ["v-eda1fc4a","/docs/algorithm/",{"y":"p","t":"Algorithm"},["/docs/algorithm/index.html"]],
]
